# ------------------------------------------------------------------------------
# i3status-rust configuration file.
#
# See "man i3status-rs" for documentation.
# https://github.com/greshake/i3status-rust
#
# For a list of available blocks:
# https://docs.rs/i3status-rs/latest/i3status_rs/blocks/index.html
# ------------------------------------------------------------------------------

[theme]
theme = "semi-native"

[icons]
icons = "awesome4"

[[block]]
block = "pomodoro"
notify_cmd = "notify-send '{msg}'"

[[block]]
block = "tea_timer"
format = " $icon {$minutes:$seconds |}"
done_cmd = "notify-send 'Timer finished'"

[[block]]
block = "music"
format = " $icon $artist - $title $prev $play $next "

[[block]]
block = "sound"

[[block]]
block = "backlight"
missing_format = ""
device = "intel_backlight"

[[block]]
block = "cpu"

[[block]]
block = "amd_gpu"
format = " $icon $utilization "
if_command = "test -e /sys/class/drm/card*-amdgpu || test -e /sys/class/drm/card*-radeon"

[[block]]
block = "nvidia_gpu"
format = " $icon $utilization "
if_command = "nvidia-smi >/dev/null 2>&1"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "

[[block]]
block = "disk_space"
format = " $icon $available "
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0

[[block]]
block = "net"
format = " $icon "
inactive_format = " $icon "

[[block]]
block = "notify"

[[block]]
block = "battery"
missing_format = ""
empty_format = ""
driver = "upower"

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%a %d/%m %R') "
