# ~/.config/yazi/yazi.toml
# See https://yazi-rs.github.io/docs/configuration/yazi

[mgr]
sort_by = "alphabetical"
sort_sensitive = false
linemode = "size" # Add size info
mouse_events = ["scroll"] # Only mouse scroll (no click etc)

