# ------------------------------------------------------------------------------
# https://wiki.archlinux.org/title/Alacritty
# https://github.com/alacritty/alacritty
# ------------------------------------------------------------------------------

[cursor.style]
blinking = "On"
shape = "Beam"

[window]
dynamic_title = true
opacity = 0.98
startup_mode = "Maximized"

[font]
size = 11.0

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

